// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHYlWExshSNkwBnoRkPHT6bhAJHgiQaA',
    appId: '1:260121636763:web:3a2ece312d2b266bc17b3e',
    messagingSenderId: '260121636763',
    projectId: 'printhub-92a6b',
    authDomain: 'printhub-92a6b.firebaseapp.com',
    storageBucket: 'printhub-92a6b.firebasestorage.app',
    measurementId: 'G-1WK7GSV9S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQsSbb351xgTUO4e40RrzhJFqCPFg_fE',
    appId: '1:260121636763:android:121cea1fe9199873c17b3e',
    messagingSenderId: '260121636763',
    projectId: 'printhub-92a6b',
    storageBucket: 'printhub-92a6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcBQCDWGN-TJNAr7imNsh54yYIDq_g62I',
    appId: '1:260121636763:ios:0f569c8f2c439af0c17b3e',
    messagingSenderId: '260121636763',
    projectId: 'printhub-92a6b',
    storageBucket: 'printhub-92a6b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcBQCDWGN-TJNAr7imNsh54yYIDq_g62I',
    appId: '1:260121636763:ios:0f569c8f2c439af0c17b3e',
    messagingSenderId: '260121636763',
    projectId: 'printhub-92a6b',
    storageBucket: 'printhub-92a6b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEHYlWExshSNkwBnoRkPHT6bhAJHgiQaA',
    appId: '1:260121636763:web:3a2ece312d2b266bc17b3e',
    messagingSenderId: '260121636763',
    projectId: 'printhub-92a6b',
    authDomain: 'printhub-92a6b.firebaseapp.com',
    storageBucket: 'printhub-92a6b.firebasestorage.app',
    measurementId: 'G-1WK7GSV9S2',
  );
}
